export const USER_CARD = "USER_CARD";
export const MODAL_CONFIRM = "MODAL_CONFIRM";
export const NEW_ORDER = "NEW_ORDER";
export const NOTIFIER = "NOTIFIER";
export const MODAL_NOTIFIER = "MODAL_NOTIFIER";
export const REQUEST_NOTIFIER = "REQUEST_NOTIFIER";
export const REQUEST_RESERVATION = "REQUEST_RESERVATION";
export const GUIDER = "GUIDER";
