/**
* USER_CARD COMPONENT INIT STATES RELATED ACTION TYPES
*/
export const USER_CARD_SCHEDULE = "USER_CARD_SCHEDULE";
export const USER_CARD_STAFF = "USER_CARD_STAFF";
export const USER_CARD_DATE = "USER_CARD_DATE";

/**
* CONDITIONAL RENDERING COMPONENT MOUNT RELATED ACTION TYPES
*/
export const MODAL_CONFIRM = "MODAL_CONFIRM";
export const NEW_ORDER = "NEW_ORDER";
export const NOTIFIER = "NOTIFIER";
export const MODAL_NOTIFIER = "MODAL_NOTIFIER";
export const REQUEST_NOTIFIER = "REQUEST_NOTIFIER";
export const REQUEST_RESERVATION = "REQUEST_RESERVATION";
export const GUIDER = "GUIDER";
export const LOADING = "LOADING";

/**
 * FullCalendar RELATED ACTION TYPES
 */
export const FULLCALENDAR_CURRENT = 'FULLCALENDAR_CURRENT';
export const FULLCALENDAR_START = 'FULLCALENDAR_START';
export const FULLCALENDAR_END = 'FULLCALENDAR_END';
export const FULLCALENDAR_BETWEEN = 'FULLCALENDAR_BETWEEN';
export const FULLCALENDAR_VIEWTYPE = 'FULLCALENDAR_VIEWTYPE';

/**
 * SCHEDULE RELATED ACTION TYPES
 */
export const REQUEST_SCHEDULE = 'REQUEST_SCHEDULE';
export const RECEIVE_SCHEDULE = 'RECEIVE_SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const SCHEDULE_CREATED = 'SCHEDULE_CREATED';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const SCHEDULE_UPDATED = 'SCHEDULE_UPDATED';

/**
 * SHOP RELATED ACTION TYPES
 */
export const SELECT_SHOP = 'SELECT_SHOP';
export const INVALIDATE_SHOP = 'INVALIDATE_SHOP';

/**
 * SHOP STAFF RELATED ACTION TYPES
 */
export const REQUEST_STAFF = 'REQUSET_STAFF';
export const RECEIVE_STAFF = 'RECEIVE_STAFF';

/**
 * SHOP SERVICE RELATED ACTION TYPES
 */
export const REQUEST_SERVICE = 'REQUEST_SERVICE';
export const RECEIVE_SERVICE = 'RECEIVE_SERVICE';

export const REQUEST_GUEST = 'REQUEST_GUEST';
export const RECEIVE_GUEST = 'RECEIVE_GUEST';
