export const USER_CARD = "USER_CARD";
export const MODAL_CONFIRM = "MODAL_CONFIRM";
export const NEW_ORDER = "NEW_ORDER";
export const NOTIFIER = "NOTIFIER";
export const MODAL_NOTIFIER = "MODAL_NOTIFIER";
export const REQUEST_NOTIFIER = "REQUEST_NOTIFIER";
export const REQUEST_RESERVATION = "REQUEST_RESERVATION";
export const GUIDER = "GUIDER";
export const LOADING = "LOADING";


/**
 * SCHEDULE RELATED ACTION TYPES
 */
export const REQUEST_SCHEDULE = 'REQUEST_SCHEDULE';
export const RECEIVE_SCHEDULE = 'RECEIVE_SCHEDULE';

/**
 * SHOP RELATED ACTION TYPES
 */
export const SELECT_SHOP = 'SELECT_SHOP';
export const INVALIDATE_SHOP = 'INVALIDATE_SHOP';